name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: チェックアウトする
        uses: actions/checkout@v4
      - name: Container registoryに認証
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker ビルドを実行する
      - run: docker build -t ghcr.io/${{ github.repository }}:latest .
      - name: Docker イメージをプッシュする
      - run: docker push ghcr.io/${{ github.repository }}:latest
